<a href="https://colab.research.google.com/github/regalleo/regalleo/blob/main/Untitled10.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
spark = SparkSession.builder.appName("CSV Reader").getOrCreate()

df1=spark.read.csv("customers.csv",inferSchema=True,header=True,sep=",")
df2=spark.read.csv("products.csv",inferSchema=True,header=True,sep=",")
df3=spark.read.csv("orders.csv",inferSchema=True,header=True,sep=",")
df4=spark.read.csv("order_items.csv",inferSchema=True,header=True,sep=",")
df5=spark.read.csv("deliveries.csv",inferSchema=True,header=True,sep=",")
df1.show()
df2.show()
df3.show()
df4.show()
df5.show()
df1.createOrReplaceTempView("cust")
df2.createOrReplaceTempView("prod")
df3.createOrReplaceTempView("ord")
df4.createOrReplaceTempView("ord_items")
df5.createOrReplaceTempView("del")

+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+
|customer_id|             name|               email|     phone|     city|      state|country|signup_date|
+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+
|    CUST001|Raj Shekhar Singh| raj.singh@gmail.com|9876543210|Bangalore|  Karnataka|  India| 2022-05-10|
|    CUST002|    Ananya Sharma|ananya.sharma@yah...|9898989898|    Delhi|      Delhi|  India| 2021-08-14|
|    CUST003|      Rahul Verma|rahul.verma@gmail...|9812345678|   Mumbai|Maharashtra|  India| 2023-01-12|
|    CUST004|       Priya Nair|priya.nair@gmail.com|9123456780|  Chennai| Tamil Nadu|  India| 2020-12-05|
|    CUST005|     Sneha Kapoor|sneha.kapoor@outl...|9911223344|Hyderabad|  Telangana|  India| 2023-03-21|
+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+

+----------+---------------+---------------+-----+----------+
|product_id|           name|       category|price|     brand|
+----------+---------------+---------------+-----+----------+
|      P100|         Laptop|    Electronics|75000|      Dell|
|      P101|          Mouse|    Electronics| 1200|  Logitech|
|      P200|     Smartphone|    Electronics|45000|   Samsung|
|      P201|     Phone Case|    Accessories|  800|    Spigen|
|      P202|     Headphones|    Electronics| 3000|      Sony|
|      P300|   Refrigerator|Home Appliances|60000|        LG|
|      P301|   Water Bottle|Home Essentials|  500|    Milton|
|      P400|Washing Machine|Home Appliances|30000|       IFB|
|      P401| Detergent Pack|Home Essentials| 1200|Surf Excel|
|      P500|          Shoes|        Fashion| 2500|      Nike|
|      P501|        Handbag|        Fashion| 3500|      Zara|
+----------+---------------+---------------+-----+----------+

+--------+-----------+----------+--------------+---------+
|order_id|customer_id|order_date|payment_method|   status|
+--------+-----------+----------+--------------+---------+
| ORD1001|    CUST001|2025-08-25|   Credit Card|Completed|
| ORD1002|    CUST002|2025-08-20|           UPI|Completed|
| ORD1003|    CUST003|2025-08-18|    Debit Card|  Pending|
| ORD1004|    CUST004|2025-08-15|   Net Banking|Completed|
| ORD1005|    CUST005|2025-08-10|           COD|  Pending|
+--------+-----------+----------+--------------+---------+

+--------+----------+--------+
|order_id|product_id|quantity|
+--------+----------+--------+
| ORD1001|      P100|       1|
| ORD1001|      P101|       2|
| ORD1002|      P200|       1|
| ORD1002|      P201|       1|
| ORD1002|      P202|       1|
| ORD1003|      P300|       1|
| ORD1003|      P301|       4|
| ORD1004|      P400|       1|
| ORD1004|      P401|       2|
| ORD1005|      P500|       2|
| ORD1005|      P501|       1|
+--------+----------+--------+

+-----------+--------+---------+-------------+---------------+
|delivery_id|order_id|  courier|delivery_date|delivery_status|
+-----------+--------+---------+-------------+---------------+
|      D1001| ORD1001| BlueDart|   2025-08-28|      Delivered|
|      D1002| ORD1002|Delhivery|         NULL|     In Transit|
|      D1003| ORD1003|     NULL|         NULL|        Pending|
|      D1004| ORD1004|    FedEx|   2025-08-19|      Delivered|
|      D1005| ORD1005|     NULL|         NULL|    Not Shipped|
+-----------+--------+---------+-------------+---------------+

In [66]:
j1=df1.join(df3,df1.customer_id==df3.customer_id,"inner")
j2=j1.join(df4,j1.order_id==df4.order_id,"inner")
j3=j2.join(df2,j2.product_id==df2.product_id,"inner")
j3.show()
j1.createOrReplaceTempView("j1")
j2.createOrReplaceTempView("j2")
j3.createOrReplaceTempView("j3")

+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+--------+-----------+----------+--------------+---------+--------+----------+--------+----------+---------------+---------------+-----+----------+
|customer_id|             name|               email|     phone|     city|      state|country|signup_date|order_id|customer_id|order_date|payment_method|   status|order_id|product_id|quantity|product_id|           name|       category|price|     brand|
+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+--------+-----------+----------+--------------+---------+--------+----------+--------+----------+---------------+---------------+-----+----------+
|    CUST001|Raj Shekhar Singh| raj.singh@gmail.com|9876543210|Bangalore|  Karnataka|  India| 2022-05-10| ORD1001|    CUST001|2025-08-25|   Credit Card|Completed| ORD1001|      P101|       2|      P101|          Mouse|    Electronics| 1200|  Logitech|
|    CUST001|Raj Shekhar Singh| raj.singh@gmail.com|9876543210|Bangalore|  Karnataka|  India| 2022-05-10| ORD1001|    CUST001|2025-08-25|   Credit Card|Completed| ORD1001|      P100|       1|      P100|         Laptop|    Electronics|75000|      Dell|
|    CUST002|    Ananya Sharma|ananya.sharma@yah...|9898989898|    Delhi|      Delhi|  India| 2021-08-14| ORD1002|    CUST002|2025-08-20|           UPI|Completed| ORD1002|      P202|       1|      P202|     Headphones|    Electronics| 3000|      Sony|
|    CUST002|    Ananya Sharma|ananya.sharma@yah...|9898989898|    Delhi|      Delhi|  India| 2021-08-14| ORD1002|    CUST002|2025-08-20|           UPI|Completed| ORD1002|      P201|       1|      P201|     Phone Case|    Accessories|  800|    Spigen|
|    CUST002|    Ananya Sharma|ananya.sharma@yah...|9898989898|    Delhi|      Delhi|  India| 2021-08-14| ORD1002|    CUST002|2025-08-20|           UPI|Completed| ORD1002|      P200|       1|      P200|     Smartphone|    Electronics|45000|   Samsung|
|    CUST003|      Rahul Verma|rahul.verma@gmail...|9812345678|   Mumbai|Maharashtra|  India| 2023-01-12| ORD1003|    CUST003|2025-08-18|    Debit Card|  Pending| ORD1003|      P301|       4|      P301|   Water Bottle|Home Essentials|  500|    Milton|
|    CUST003|      Rahul Verma|rahul.verma@gmail...|9812345678|   Mumbai|Maharashtra|  India| 2023-01-12| ORD1003|    CUST003|2025-08-18|    Debit Card|  Pending| ORD1003|      P300|       1|      P300|   Refrigerator|Home Appliances|60000|        LG|
|    CUST004|       Priya Nair|priya.nair@gmail.com|9123456780|  Chennai| Tamil Nadu|  India| 2020-12-05| ORD1004|    CUST004|2025-08-15|   Net Banking|Completed| ORD1004|      P401|       2|      P401| Detergent Pack|Home Essentials| 1200|Surf Excel|
|    CUST004|       Priya Nair|priya.nair@gmail.com|9123456780|  Chennai| Tamil Nadu|  India| 2020-12-05| ORD1004|    CUST004|2025-08-15|   Net Banking|Completed| ORD1004|      P400|       1|      P400|Washing Machine|Home Appliances|30000|       IFB|
|    CUST005|     Sneha Kapoor|sneha.kapoor@outl...|9911223344|Hyderabad|  Telangana|  India| 2023-03-21| ORD1005|    CUST005|2025-08-10|           COD|  Pending| ORD1005|      P501|       1|      P501|        Handbag|        Fashion| 3500|      Zara|
|    CUST005|     Sneha Kapoor|sneha.kapoor@outl...|9911223344|Hyderabad|  Telangana|  India| 2023-03-21| ORD1005|    CUST005|2025-08-10|           COD|  Pending| ORD1005|      P500|       2|      P500|          Shoes|        Fashion| 2500|      Nike|
+-----------+-----------------+--------------------+----------+---------+-----------+-------+-----------+--------+-----------+----------+--------------+---------+--------+----------+--------+----------+---------------+---------------+-----+----------+

In [65]:
# Find the total revenue generated by each city.
spark.sql("select city,sum(price) as total_revenue from j3 group by city").show()
# Get the top 5 customers who spent the most across all orders.
spark.sql("select c.name as customer_name,sum(p.price*oi.quantity) as total_spent from cust c join ord o on o.customer_id=c.customer_id join ord_items oi on oi.order_id=o.order_id join prod p on p.product_id=oi.product_id group by customer_name order by total_spent desc limit 5").show()
# Find the average order value per customer.
spark.sql("select c.name as customer_name,avg(p.price*oi.quantity) as avg_order_value from cust c join ord o on o.customer_id=c.customer_id join ord_items oi on oi.order_id=o.order_id join prod p on p.product_id=oi.product_id group by customer_name").show()
# Count the number of distinct customers per state.
spark.sql("select count(distinct c.customer_id) as unique_customers,state from cust c group by state ").show()
# Find the most popular product category in each city.
spark.sql("select c.city,p.category,sum(oi.quantity) as popular_product from cust c join ord o on o.customer_id=c.customer_id join ord_items oi on oi.order_id=o.order_id join prod p on p.product_id=oi.product_id group by c.city,p.category order by c.city,popular_product desc").show()
# List customers who have placed more than 5 orders.
spark.sql("select c.name as customer_name,sum(oi.quantity) as total_orders from cust c join ord o on o.customer_id=c.customer_id join ord_items oi on oi.order_id=o.order_id group by customer_name having total_orders>5").show()

# joined_final=spark.sql("select * from cust c join ord o on o.customer_id=c.customer_id join ord_items oi on oi.order_id=o.order_id").show()
# joined_final.createOrReplaceTempView("joined_final")
# Find orders with more than 3 unique products.
spark.sql("select o.order_id,count(distinct oi.product_id) as unique_products from ord o join ord_items oi on oi.order_id=o.order_id group by o.order_id having count(distinct oi.product_id)>3").show()
# Find customers who never placed an order.
spark.sql("select c.name as customer_name,o.order_id from cust c left join ord o on c.customer_id=o.customer_id where o.order_id is null").show()
# Calculate the average delivery time (in days) per courier.
spark.sql("select d.courier, avg(datediff(d.delivery_date,o.order_date)) as avg_delivery_time from del d join ord o on o.order_id=d.order_id where d.delivery_date is not null group by d.courier").show()
# Find the city with the highest number of pending deliveries.
spark.sql("select c.city,count(*) as pending_deliveries from cust c join ord o on o.customer_id=c.customer_id join del d on d.order_id=o.order_id where d.delivery_status='Pending' group by c.city order by pending_deliveries desc limit 1").show()
# Identify customers with total purchases > ₹1,00,000.
spark.sql("select c.name,sum(p.price*oi.quantity) as total_purchase from cust c join ord o on c.customer_id=o.customer_id join ord_items oi on oi.order_id=o.order_id join prod p on p.product_id=oi.product_id group by c.name having total_purchase >100000 order by total_purchase desc").show()
# Find orders where at least one item price > 50,000.
spark.sql("select o.order_id,p.price from ord o join ord_items oi on oi.order_id=o.order_id join prod p on p.product_id=oi.product_id where p.price>50000").show()
# Get the most popular product in each category.
spark.sql("select p.product_id,p.category,sum(oi.quantity) as popular_product from prod p join ord_items oi on oi.product_id=p.product_id group by p.product_id,p.category order by popular_product desc").show()
# Count orders by payment method.
spark.sql("select payment_method,count(*) from ord group by payment_method").show()
# Get all orders placed within the last 30 days.
spark.sql("select o.order_id,o.order_date,c.name as customer_name from cust c join ord o on o.customer_id=c.customer_id where datediff(current_date(),order_date)<=30").show()
# Find products that have never been ordered.
spark.sql("select p.product_id,o.order_id from prod p left join ord_items oi on oi.product_id=p.product_id left join ord o on o.order_id=oi.order_id where o.order_id is null").show()

+---------+-------------+
|     city|total_revenue|
+---------+-------------+
|Bangalore|        76200|
|  Chennai|        31200|
|   Mumbai|        60500|
|    Delhi|        48800|
|Hyderabad|         6000|
+---------+-------------+

+-----------------+-----------+
|    customer_name|total_spent|
+-----------------+-----------+
|Raj Shekhar Singh|      77400|
|      Rahul Verma|      62000|
|    Ananya Sharma|      48800|
|       Priya Nair|      32400|
|     Sneha Kapoor|       8500|
+-----------------+-----------+

+-----------------+------------------+
|    customer_name|   avg_order_value|
+-----------------+------------------+
|      Rahul Verma|           31000.0|
|Raj Shekhar Singh|           38700.0|
|    Ananya Sharma|16266.666666666666|
|     Sneha Kapoor|            4250.0|
|       Priya Nair|           16200.0|
+-----------------+------------------+

+----------------+-----------+
|unique_customers|      state|
+----------------+-----------+
|               1|  Karnataka|
|               1| Tamil Nadu|
|               1|      Delhi|
|               1|Maharashtra|
|               1|  Telangana|
+----------------+-----------+

+---------+---------------+---------------+
|     city|       category|popular_product|
+---------+---------------+---------------+
|Bangalore|    Electronics|              3|
|  Chennai|Home Essentials|              2|
|  Chennai|Home Appliances|              1|
|    Delhi|    Electronics|              2|
|    Delhi|    Accessories|              1|
|Hyderabad|        Fashion|              3|
|   Mumbai|Home Essentials|              4|
|   Mumbai|Home Appliances|              1|
+---------+---------------+---------------+

+-------------+------------+
|customer_name|total_orders|
+-------------+------------+
+-------------+------------+

+--------+---------------+
|order_id|unique_products|
+--------+---------------+
+--------+---------------+

+-------------+--------+
|customer_name|order_id|
+-------------+--------+
+-------------+--------+

+--------+-----------------+
| courier|avg_delivery_time|
+--------+-----------------+
|BlueDart|              3.0|
|   FedEx|              4.0|
+--------+-----------------+

+------+------------------+
|  city|pending_deliveries|
+------+------------------+
|Mumbai|                 1|
+------+------------------+

+----+--------------+
|name|total_purchase|
+----+--------------+
+----+--------------+

+--------+-----+
|order_id|price|
+--------+-----+
| ORD1001|75000|
| ORD1003|60000|
+--------+-----+

+----------+---------------+---------------+
|product_id|       category|popular_product|
+----------+---------------+---------------+
|      P301|Home Essentials|              4|
|      P101|    Electronics|              2|
|      P500|        Fashion|              2|
|      P401|Home Essentials|              2|
|      P201|    Accessories|              1|
|      P400|Home Appliances|              1|
|      P501|        Fashion|              1|
|      P202|    Electronics|              1|
|      P100|    Electronics|              1|
|      P200|    Electronics|              1|
|      P300|Home Appliances|              1|
+----------+---------------+---------------+

+--------------+--------+
|payment_method|count(1)|
+--------------+--------+
|           COD|       1|
|   Credit Card|       1|
|   Net Banking|       1|
|    Debit Card|       1|
|           UPI|       1|
+--------------+--------+

+--------+----------+-----------------+
|order_id|order_date|    customer_name|
+--------+----------+-----------------+
| ORD1001|2025-08-25|Raj Shekhar Singh|
| ORD1002|2025-08-20|    Ananya Sharma|
| ORD1003|2025-08-18|      Rahul Verma|
| ORD1004|2025-08-15|       Priya Nair|
| ORD1005|2025-08-10|     Sneha Kapoor|
+--------+----------+-----------------+

+----------+--------+
|product_id|order_id|
+----------+--------+
+----------+--------+

In [61]:
# Here are 4 Spark SQL practice questions on CONCAT (only questions, no solutions):

# Create a full customer address by concatenating city, state, and country into a single column.
spark.sql("select name,concat(city,',',state,',',country) as full_address from cust").show()
# Generate unique order reference IDs by concatenating order_id with customer_id.
spark.sql("select order_id,customer_id,concat(order_id,'-',customer_id) as unique_id from ord").show()
# Show customer name along with their email domain in the format "Name (domain)".
spark.sql("select name,concat(name,'(',split(email,'@')[1],')') as name_email from cust").show()
# Create a delivery summary message like: “Order ORD1001 for Raj Shekhar Singh is Delivered by
spark.sql("select concat('Order ',o.order_id,' for',c.name,' is Delivered by ',d.courier) as delivery_message from cust c join ord o on o.customer_id=c.customer_id join del d on d.order_id=o.order_id").show()

+-----------------+--------------------+
|             name|        full_address|
+-----------------+--------------------+
|Raj Shekhar Singh|Bangalore,Karnata...|
|    Ananya Sharma|   Delhi,Delhi,India|
|      Rahul Verma|Mumbai,Maharashtr...|
|       Priya Nair|Chennai,Tamil Nad...|
|     Sneha Kapoor|Hyderabad,Telanga...|
+-----------------+--------------------+

+--------+-----------+---------------+
|order_id|customer_id|      unique_id|
+--------+-----------+---------------+
| ORD1001|    CUST001|ORD1001-CUST001|
| ORD1002|    CUST002|ORD1002-CUST002|
| ORD1003|    CUST003|ORD1003-CUST003|
| ORD1004|    CUST004|ORD1004-CUST004|
| ORD1005|    CUST005|ORD1005-CUST005|
+--------+-----------+---------------+

+-----------------+--------------------+
|             name|          name_email|
+-----------------+--------------------+
|Raj Shekhar Singh|Raj Shekhar Singh...|
|    Ananya Sharma|Ananya Sharma(yah...|
|      Rahul Verma|Rahul Verma(gmail...|
|       Priya Nair|Priya Nair(gmail....|
|     Sneha Kapoor|Sneha Kapoor(outl...|
+-----------------+--------------------+

+--------------------+
|    delivery_message|
+--------------------+
|Order ORD1001 for...|
|Order ORD1002 for...|
|                NULL|
|Order ORD1004 for...|
|                NULL|
+--------------------+